export const WITHDRAW_FEED_PAGE_SIZE = 20;
export const WITHDRAW_FEED_ITEM_HEIGHT = 148;
export const WITHDRAW_FEED_OVERSCAN = 3;
export const WITHDRAW_FEED_VIEWPORT_HEIGHT = 420;
export const WITHDRAW_FEED_LOAD_MORE_THRESHOLD = 120;
